In [ ]:
#Importing the dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Loading the dataset
data = pd.read_csv('/content/Dataset .csv')

In [ ]:
#Displaying the first 5 lines of the dataset
data.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [ ]:
#Displaying the last 5 lines of the dataset
data.tail()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [ ]:
#Information of the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [ ]:
#Describing the dataset
data.describe()

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [ ]:
#Numeical and categorical featurs of the dataset
numerical_features = data.select_dtypes(include=['int64','float64'])
categorical_features = data.select_dtypes(include=['object'])

In [ ]:
data.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
#Encoding the categorical feature by label encoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

categorical_featuers_encoded = categorical_features.copy()
for col in categorical_featuers_encoded:
 categorical_featuers_encoded[col] = label_encoder.fit_transform(categorical_featuers_encoded[col])

In [ ]:
print("Enter the cuisine for your preference")
cuisine_preference = input().strip('"')
print("Enter the maxiumum price for the user")
max_price = int(input())
#filtering the data into user choices
if 'cuisine' in data.columns:
  recommended_restaurants = data[
    (data['cuisine'] == cuisine_preference)&(data['price']<=max_price)
  ]
  print(recommended_restaurants)
else:
  print("Column 'cuisine' not found in the data")

Enter the cuisine for your preference
"Japanese"
Enter the maxiumum price for the user
30
Column 'cuisine' not found in the data

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
feature_matrix = categorical_featuers_encoded.values
similarity_matrix = cosine_similarity(feature_matrix)

preferred_restaurant_index = 0
similar_restaurants_indices = similarity_matrix[preferred_restaurant_index].argsort()[::-1][1:]
print("Top 5 similar restuarants:")
for index in similar_restaurants_indices[:5]:
  print(data.iloc[index])

Top 5 similar restuarants:
Restaurant ID                                                    18377936
Restaurant Name                                                    Liquid
Country Code                                                            1
City                                                               Kanpur
Address                 The Terrace, Ratan Zone, Coca-Cola Crossing, A...
Locality                                                      Ashok Nagar
Locality Verbose                                      Ashok Nagar, Kanpur
Longitude                                                       80.313458
Latitude                                                        26.471529
Cuisines                Finger Food, North Indian, Continental, Italia...
Average Cost for two                                                 1000
Currency                                               Indian Rupees(Rs.)
Has Table booking                                                      No
Has Online delivery                                                    No
Is delivering now                                                      No
Switch to order menu                                                   No
Price range                                                             3
Aggregate rating                                                      4.0
Rating color                                                        Green
Rating text                                                     Very Good
Votes                                                                  24
Name: 2361, dtype: object
Restaurant ID                                307935
Restaurant Name                         Kusum Rolls
Country Code                                      1
City                                        Gurgaon
Address                 U-1/9, DLF Phase 3, Gurgaon
Locality                                DLF Phase 3
Locality Verbose               DLF Phase 3, Gurgaon
Longitude                                 77.092692
Latitude                                  28.490744
Cuisines                         Fast Food, Chinese
Average Cost for two                            350
Currency                         Indian Rupees(Rs.)
Has Table booking                                No
Has Online delivery                             Yes
Is delivering now                                No
Switch to order menu                             No
Price range                                       1
Aggregate rating                                3.1
Rating color                                 Orange
Rating text                                 Average
Votes                                            71
Name: 1361, dtype: object
Restaurant ID                                                      301728
Restaurant Name                                              Desire Foods
Country Code                                                            1
City                                                            Faridabad
Address                 G 25/22, Main Road, 40 Feet, Molarband Extensi...
Locality                                                  Badarpur Border
Locality Verbose                               Badarpur Border, Faridabad
Longitude                                                        77.30664
Latitude                                                        28.490059
Cuisines                                       Chinese, Fast Food, Bakery
Average Cost for two                                                  250
Currency                                               Indian Rupees(Rs.)
Has Table booking                                                      No
Has Online delivery                                                    No
Is delivering now                                                      No
Switch to order menu                                                   No
Price range                                                             1
Aggregate rating                                                      2.9
Rating color                                                       Orange
Rating text                                                       Average
Votes                                                                   4
Name: 865, dtype: object
Restaurant ID                                                      304687
Restaurant Name                                                Garden Hut
Country Code                                                            1
City                                                            New Delhi
Address                 Maharaja Surajmal Samadhi Park, Opposite C Blo...
Locality                                                      Anand Vihar
Locality Verbose                                   Anand Vihar, New Delhi
Longitude                                                       77.305701
Latitude                                                        28.660128
Cuisines                                               Chinese, Fast Food
Average Cost for two                                                  250
Currency                                               Indian Rupees(Rs.)
Has Table booking                                                      No
Has Online delivery                                                    No
Is delivering now                                                      No
Switch to order menu                                                   No
Price range                                                             1
Aggregate rating                                                      3.1
Rating color                                                       Orange
Rating text                                                       Average
Votes                                                                  13
Name: 2644, dtype: object
Restaurant ID                                                        2913
Restaurant Name                                             Gola Sizzlers
Country Code                                                            1
City                                                            New Delhi
Address                 K-24, Opposite PVR Plaza Cinema, Connaught Pla...
Locality                                                  Connaught Place
Locality Verbose                               Connaught Place, New Delhi
Longitude                                                       77.219858
Latitude                                                         28.63525
Cuisines                      Chinese, North Indian, Mughlai, Continental
Average Cost for two                                                 1600
Currency                                               Indian Rupees(Rs.)
Has Table booking                                                      No
Has Online delivery                                                   Yes
Is delivering now                                                      No
Switch to order menu                                                   No
Price range                                                             3
Aggregate rating                                                      3.0
Rating color                                                       Orange
Rating text                                                       Average
Votes                                                                 671
Name: 3006, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

relevant_columns = ['Restaurant Name', 'City', 'Cuisines', 'Price range', 'Aggregate rating']

# Extract relevant features
features = data[relevant_columns].copy()

features['combined_features'] = features.apply(lambda row: ' '.join(row.dropna().astype(str)), axis=1)

# Create a TF-IDF Vectorizer to convert text data into numerical data
tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(features['combined_features'])

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# Function to get recommendations based on user preferences
def get_recommendations(preferences, cosine_sim=cosine_sim):
    user_tfidf = tfidf.transform([preferences])
    user_similarities = linear_kernel(user_tfidf, tfidf_matrix)
    sim_scores = list(enumerate(user_similarities[0]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    top_indices = [i[0] for i in sim_scores[:10]]
    return data.iloc[top_indices][['Restaurant Name', 'City', 'Cuisines', 'Price range', 'Aggregate rating']]

sample_preferences = "Japanese Makati City 3 4.5"
recommended_restaurants = get_recommendations(sample_preferences)
print(recommended_restaurants)

                            Restaurant Name              City  \
1                          Izakaya Kikufuji       Makati City
0                          Le Petit Souffle       Makati City
480            Fuji Bay Japanese Restaurant        Sioux City
9334                               wagamama   Wellington City
3102               Fuji Japanese Restaurant         New Delhi
491   Tokyo Japanese Steakhouse & Sushi Bar        Sioux City
5417             Manami Japanese Restaurant         New Delhi
3                                      Ooma  Mandaluyong City
8629                               City Hut             Noida
927                              City Dhaba         Faridabad

                        Cuisines  Price range  Aggregate rating
1                       Japanese            3               4.5
0     French, Japanese, Desserts            3               4.8
480              Japanese, Sushi            3               3.7
9334             Japanese, Asian            4               3.7
3102                    Japanese            4               4.0
491       Japanese, Steak, Sushi            3               3.9
5417                    Japanese            3               0.0
3                Japanese, Sushi            4               4.9
8629       North Indian, Chinese            2               2.5
927        North Indian, Chinese            2               0.0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
relevant_columns = ['Restaurant Name', 'City', 'Cuisines','Price range', 'Aggregate rating']
features = data[relevant_columns].copy()

# Convert 'Price range' and 'Aggregate rating' to strings before concatenation and fill NaN with empty strings
features['combined_features'] = features['Restaurant Name'] + '  '+ features['City'] + '  ' + features['Cuisines'] + '  ' + features['Price range'].astype(str) + '  ' + features['Aggregate rating'].astype(str)
features['combined_features'] = features['combined_features'].fillna('') # Fill NaN values with empty strings

tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(features['combined_features'])

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

def get_recommendations(preferences, cosine_sim=cosine_sim):
  user_tfidf = tfidf.transform([preferences])
  user_similarities = linear_kernel(user_tfidf, tfidf_matrix)

  sim_scores = list(enumerate(user_similarities[0]))
  sim_scores = sorted(sim_scores, key =lambda x:x[1],reverse=True)

  top_indices = [i[0] for i in sim_scores[:10]]

  return data.iloc[top_indices][['Restaurant Name', 'City','Cuisines','Price range','Aggregate rating']]

sample_preferences = "Japanese Makati City 3 4.5"
recommended_restaurants = get_recommendations(sample_preferences)
print(recommended_restaurants)

                            Restaurant Name              City  \
1                          Izakaya Kikufuji       Makati City
0                          Le Petit Souffle       Makati City
480            Fuji Bay Japanese Restaurant        Sioux City
9334                               wagamama   Wellington City
3102               Fuji Japanese Restaurant         New Delhi
491   Tokyo Japanese Steakhouse & Sushi Bar        Sioux City
5417             Manami Japanese Restaurant         New Delhi
3                                      Ooma  Mandaluyong City
8629                               City Hut             Noida
927                              City Dhaba         Faridabad

                        Cuisines  Price range  Aggregate rating
1                       Japanese            3               4.5
0     French, Japanese, Desserts            3               4.8
480              Japanese, Sushi            3               3.7
9334             Japanese, Asian            4               3.7
3102                    Japanese            4               4.0
491       Japanese, Steak, Sushi            3               3.9
5417                    Japanese            3               0.0
3                Japanese, Sushi            4               4.9
8629       North Indian, Chinese            2               2.5
927        North Indian, Chinese            2               0.0